# generated by chat-gpt question:
# could you provide a snippet that uses langchain that query json data and answer questions on that data?

import json
import langchain

# Load the JSON data
with open("src/chatJsonData.json", "r") as f:
    data = json.load(f)

def query_data(query):
    # Create a LangChain instance and set the data as the knowledge base
    lc = langchain.LangChain()
    lc.set_knowledge_base(data)

    # Generate a response
    response = lc.generate_response(query)

    return response

# Example usage
print(query_data("What is the name of the company?"))
print(query_data("What is the revenue?"))
print(query_data("How many employees does the company have?"))